### ISSUE TITLE
关于电阻测试版

### ISSUE THREAD

**Issue by megaduo** [oldgerman/mR-71-RE#1]
您好，能否增加一个分板版的电阻测试板gerber，从中间白线出一分为二，方便打板，谢谢

**Comment by oldgerman** [comment]
> 您好，能否增加一个分板版的电阻测试板gerber，从中间白线出一分为二，方便打板，谢谢

你好，改好的Gerber已上传：[PCB预览](https://github.com/oldgerman/mR-71-RE/blob/master/Gerber/Kelvin_RES/README.md)
PS：因为PCB板厂一般要求PCB最窄处大于等于5mm，所以从白线分开后，加宽到5mm了

**Comment by megaduo** [comment]
感谢！
